dwc_otg_dir-$(CONFIG_ARCH_MESON1) := 220/
dwc_otg_dir-$(CONFIG_ARCH_MESON2) := 220/
dwc_otg_dir-$(CONFIG_ARCH_MESON3) := 220/
dwc_otg_dir-$(CONFIG_ARCH_MESON6) := 294/

obj-$(CONFIG_USB_DWC_OTG_HCD)	+= $(dwc_otg_dir-y)
