#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_SENSORS_MMC314X)      += mmc31xx.o
obj-$(CONFIG_SENSORS_MMA8452)   += mma8452.o
obj-$(CONFIG_SENSORS_MMA7660)   += mma7660.o
obj-$(CONFIG_SENSORS_MMC328X)   += mmc328x.o
obj-$(CONFIG_SENSORS_MMC328XMA)    += mmc328x.o
obj-$(CONFIG_ECOMPASS)          += mecs.o
obj-$(CONFIG_BOSCH_BMA250)      += bma250.o
obj-$(CONFIG_BOSCH_BMA250_MEMSIC)      += bma250_memsic.o
obj-$(CONFIG_BOSCH_BMA222)      += bma222.o
