#
# Makefile for tuners.
#

obj-$(CONFIG_TVIN_TUNER_FQ1216ME) += tvin_fq1216me.o
tvin_fq1216me-objs := tvin_tuner_driver.o fq1216me_tuner.o fq1216me_demod.o

obj-$(CONFIG_TVIN_TUNER_HTM9AW125) += tvin_htm9aw125.o
tvin_htm9aw125-objs := tvin_tuner_driver.o htm9aw125_tuner.o htm9aw125_demod.o

obj-$(CONFIG_TVIN_TUNER_SI2176) += tvin_si2176.o
tvin_si2176-objs := tvin_tuner_driver.o si2176_tuner.o si2176_func.o


